import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";


import { AuthProvider } from "@/context/authContext";
import { GoogleOAuthProvider } from '@react-oauth/google';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const API_URL = (process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000').replace(/\/$/, '');
  let googleClientId = '';

  try {
    const res = await fetch(`${API_URL}/api/admin/settings/public`, { 
      next: { revalidate: 3600 },
      headers: { 'Accept': 'application/json' }
    });
    
    if (res.ok) {
      const result = await res.json();
      if (result.data) {
        googleClientId = result.data.socialLogin?.google?.clientId || '';
      }
    } else {
      console.error('Settings API returned error:', res.status);
    }
  } catch (error) {
    console.error('Failed to fetch social settings in layout:', error);
  }

  // To prevent the "Missing required parameter client_id" error, we must provide a string.
  // If the server-side fetch fails, the frontend will try again in AuthContext.
  const finalClientId = googleClientId || "placeholder-id";

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
   
      <body className="min-h-full flex flex-col bg-[#fef3f6]">
        <GoogleOAuthProvider clientId={finalClientId}>
          <AuthProvider>
            {children}
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
   
    </html>
  );
}
